spring:
  application:
    name: "backend"
  datasource:
    url: jdbc:postgresql://localhost:5432/saru
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

file-storage:
  base-path: ${FILE_BASE_PATH:/app/files}

jellyfin:
  apiKey: ${JELLYFIN_KEY:}
  username: ${JELLYFIN_USERNAME:}
  password: ${JELLYFIN_PASSWORD:}